# Tại sao dùng application.yml
#  - Tốc độ load file nhanh hơn application.properties và cấu trúc dạng tree đễ đọc, ngắn gọn hơn
#  - Nó là Best Practice cho các cấu hình cần load lên trong thời điểm Compile-time như: cấu hình Database,...

server:
  port: 8080

spring:
  application:
    name: comic
  output:
    ansi:
      enabled: DETECT

api:
  prefix:
    v1: /api/v1

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: DEBUG
    com:
      group17:
        comic:
          service: INFO
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} - %m%n %ex{short}'
    file: '%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

comic:
  api:
    document_name: Comic API Documentation
    description: This is the api comic documentation only for the group 17 :V
    version: v1.0.0
    server:
      local:
        url: http://localhost:${server.port}
        description: Local server      
  base_dir: /src/main/java/com/group17/comic
  plugin:
    crawler:
      crawler_package_name: com.group17.comic.plugins.crawler.concretes
      crawler_directory: /plugins/crawler/concretes
      default_crawler_name: Tang Thu Vien 
    converter:
      converter_package_name: com.group17.comic.plugins.exporter.concretes
      converter_directory: /plugins/exporter/concretes
      default_converter_name: PDF
      api_key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWMyOGFlMmExZjlhMDhjMWZhNTYzN2NlOGMwMjUyMmEwYTA5YTIyNzI0Mjg0M2JjODdkMzM0ZWRmYTc0MTk1ZDQzMmJmY2FmNTMxNTcwYzQiLCJpYXQiOjE3MTY2MDMwNjcuNzQ0MDExLCJuYmYiOjE3MTY2MDMwNjcuNzQ0MDE0LCJleHAiOjQ4NzIyNzY2NjcuNzIzMzc1LCJzdWIiOiI2ODQ4NTY3NiIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.ORRDLBHXHbA3bMc8Q5aBGWogBfnvTsvguO-QcA7X2zla8EzhG7mtURD8gtop2Np3KMjszay_bASs1B2iuEx1m3mYF5nt_yDkidSru94jt5NqL-UdbiEgrkYhf9iNGtJdH2bS4gGGvJKdSGnluH5waZ-jKwws8Vz87T8zZwlk9GVp1-Tlom_XLiMIgwV6WLFv4uuDRN4EnirgC4PjNh_zh6So0FDN7cw7QnYEtkpTW8S1VSZSzLkSjqdBPTf6PpuUj63YZdWVod1OveOavupEvJnYIH4k-w3KLaooGP31TOKT5nwZipV0lqLV5nAvnt58PDcdaz3o6oLh6lyHZ29n5XIEb5EuWouaSByvnULsrH4dplhCQmIdpc_r40UGDZ-DXxBcR60g_0SEEkUGlcziHkV7JLWRSRCChF4PJFOBpsPvrO2vomOBtLDw0KJPWYYCb1kaFAqzrttvbYV06R7g9e5UnQlQ5UuCwz-sgwNPIHa77oe-3lia7tJT4U4wS_ksurIiVHPjeSme7QsWSksY6abD5j47Ijj07AtsaDZ_8dallmVfFfU0DVHMeEK1VMmkBJsa7URDakxXdedfhWpdRhUcgxs85HvkYdYb7yINu4WH1BvNPes-4z4awVq9wGOuxhVN-OzGgTS1Do9R_BFg6VxnHmrlbrhIaPIa4uryo8s

# Cấu hình profile: 

# - Build project thành file jar. Có một số profile như dev, test, uat, prod
# - Sau khi build thì sẽ triển khai file jar môi trường dev lên Docker. Why to use Docker?
# * Cách đây hơn chục năm trước, khi đầy file jar lên máy chủ nào đó mà để máy chủ đó chạy file này được thì nó cần 
# phải được set-up thủ công như cài đặt web server(Tomcat, JBoss hay Glassfish), cài JDK, cấu hình path evironment
# (như JAVA_HOME), cài shell-script đề chạy script để phân quyền,... và một số cài đặt khác. Thật là khổ d* 
# => The Savior: DOCKER. Oh yeah, với docker mình sẽ tạo một image bằng cách viết kịch bản(senario)
# vào một file tên là Dockerfile. Docker sẽ dựa vào Dockerfile và tự set-up tạo ra một image. 
# => Ngoài Docker thì có một công cự quản lí container tiên tiến hơn đó là Kubernetes